// <auto-generated />
using System;
using EventProgram.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventProgram.Infrastructure.Migrations
{
    [DbContext(typeof(EventProgramDbContext))]
    [Migration("20260905082110_AddDemoEvents")]
    partial class AddDemoEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventProgram.Domain.Entities.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessPasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ShareCode")
                        .IsUnique();

                    b.ToTable("events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b412d60-9f32-4c1e-b2b4-938c351d67fe"),
                            Capacity = 80,
                            CreatedAtUtc = new DateTime(2026, 9, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yeni başlayan geliştiriciler için proje fikri, portföy ve kariyer üzerine açık demo etkinliği.",
                            EndsAtUtc = new DateTime(2030, 6, 15, 19, 0, 0, 0, DateTimeKind.Utc),
                            OwnerId = new Guid("f7ac607a-36ed-4bb6-b952-b8fb76a1f764"),
                            ShareCode = "8b52222e9e064b1badc429ed86f8f41a",
                            StartsAtUtc = new DateTime(2030, 6, 15, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Published",
                            Title = "Yazılım Topluluğu Buluşması",
                            UpdatedAtUtc = new DateTime(2026, 9, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Visibility = "Public"
                        },
                        new
                        {
                            Id = new Guid("76a7c9a3-5760-4c41-b272-6f08f2c9f203"),
                            Capacity = 20,
                            CreatedAtUtc = new DateTime(2026, 9, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yalnızca davet bağlantısını alan kişiler için private etkinlik örneği.",
                            EndsAtUtc = new DateTime(2030, 7, 10, 19, 30, 0, 0, DateTimeKind.Utc),
                            OwnerId = new Guid("f7ac607a-36ed-4bb6-b952-b8fb76a1f764"),
                            ShareCode = "c8395aa8141c438d9c740627e8c493c3",
                            StartsAtUtc = new DateTime(2030, 7, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Published",
                            Title = "EventProgram Kapalı Test Oturumu",
                            UpdatedAtUtc = new DateTime(2026, 9, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Visibility = "Private"
                        });
                });

            modelBuilder.Entity("EventProgram.Domain.Entities.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7ac607a-36ed-4bb6-b952-b8fb76a1f764"),
                            CreatedAtUtc = new DateTime(2026, 9, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "EventProgram Demo",
                            Email = "demo@eventprogram.local",
                            GoogleSubject = "eventprogram-demo-owner",
                            IsBlocked = false,
                            Role = "User"
                        });
                });

            modelBuilder.Entity("EventProgram.Domain.Entities.Events.Event", b =>
                {
                    b.HasOne("EventProgram.Domain.Entities.Users.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
